### ISSUE TITLE
Import paths should be relative instead of absolute.

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-creator-classic#5]
Classic creator uses absolute paths for importing modules eg
https://github.com/ckeditor/ckeditor5-creator-classic/blob/master/src/classiccreator.js#L8

It causes problem with bundling, rollup treats absolute paths as external dependencies and exclude it from package.

**Comment by Reinmar** [comment]
Absolute paths are for tests. Source code should use relative paths only.

**Comment by oskarwrobel** [comment]
I just found some new imports with absolute path.

**Comment by oskarwrobel** [comment]
Sorry not this repository.

**Comment by Reinmar** [comment]
Will be fixed by #9.
